# Site settings
title: FdelMazo
email: federicodelmazo@hotmail.com
url: https://fdelmazo.github.io

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

social:
  - title: github
      url: http://github.com/FdelMazo
  - title: facebook
    url: http://facebook.com/FdelMazo

# Build settings
markdown: kramdown
permalink: pretty
