# Site settings
title: Federico del Mazo
email: fdelmazo@fi.uba.ar
url: https://fede.dm
description: Personal portfolio website, with projects, collaborations, and stuff
author: https://github.com/FdelMazo/

google_analytics: "UA-142870087-1"

# Build settings
markdown: kramdown
permalink: pretty
