# Site settings
title: Federico del Mazo
email: fdelmazo@fi.uba.ar
url: https://fdelmazo.github.io
description: Proyectos y Colaboraciones
author: Federico del Mazo

# original theme: https://github.com/jeromelachaud/freelancer-theme

color:
  primary: 168, 237, 234
  primary-dark: 35, 49, 64
  secondary: 254, 214, 227
  secondary-dark: 248, 107, 152

# Build settings
markdown: kramdown
permalink: pretty
