# Site settings
title: FdelMazo
email: fdelmazo@fi.uba.ar
url: https://fdelmazo.github.io
description: Proyectos y Colaboraciones
author: FdelMazo

# original theme: https://github.com/jeromelachaud/freelancer-theme

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  background: aliceblue

# Build settings
markdown: kramdown
permalink: pretty
