# Site settings
title: Federico del Mazo
email: fdelmazo@fi.uba.ar
url: https://fdelmazo.github.io
description: Personal portfolio website, with projects, collaborations, and stuff
author: https://github.com/FdelMazo/

google_analytics: "UA-142870087-1"

# original theme: https://github.com/jeromelachaud/freelancer-theme

color:
  primary: 168, 237, 234
  primary-dark: 35, 49, 64
  secondary: 254, 214, 227
  secondary-dark: 248, 107, 152

# Build settings
markdown: kramdown
permalink: pretty
